### ISSUE TITLE
Cannot run code

### ISSUE THREAD

**Issue by whizkid77** [Lohit9/mobile-buy-sdk-react-native-sample#1]
Hi, please see the attached error screenshot.  Thanks!

To reproduce:
1. `git clone` this repo
2. `npm install`
3. add api key, store domain, and channel id
4. run in xcode

![screen shot 2016-03-11 at 2 13 01 pm](https://cloud.githubusercontent.com/assets/2087689/13716988/65a60294-e793-11e5-8def-32efd6412282.png)

**Comment by gholevas** [comment]
There is a spelling error. On line 3 of List.js change BuySDKManager to BuySdkManager

**Comment by Lohit9** [comment]
[Fixed](https://github.com/Lohit9/mobile-buy-sdk-react-native-sample/commit/a92937a8795fb2dd69d0c3d918dcd478ae205f67). Thank you
